### ISSUE TITLE
Нерабочая проверка на безопасность прыжка

### ISSUE THREAD

**Issue by projectatom** [TxN/MC-WarpMaster#1]
1508 строка в Main.lua, ты пытаешься сравнить nil и false, но это не одно и то же
![6ezci20](https://user-images.githubusercontent.com/18503003/27304863-27c3b6dc-5548-11e7-8a0c-05a89c7a4f9e.png)

**Comment by TxN** [comment]
Конкретно это не баг, специально так сделано, чтобы условие никогда не срабатывало, потому что MakePreflightCheck работает криво.
Надо будет пофиксить проверку, и убрать это.

**Comment by TxN** [comment]
Добавил обнуление данных о планируемом прыжке при старте программы. 
По идее должно починить проверку.
Также сделал возможность игнорировать предупреждение безопасности.
